### PR TITLE
I had a problem figuring out what it was doing before. This reads better 

### PR DESCRIPTION
**Pull request by dscataglini**
I had a problem figuring out what it was doing before. This reads better to me and it loops only once.

### CODE REVIEW

**Comment by dscataglini** [comment]
Btw, would it be ok to change the interests from a string to its own class?
Right now you can't have commas inside of your interests but it's probably ok.

**Comment by lenary** [comment]
This looks good. The tests pass?

**Comment by dscataglini** [comment]
Yes, after I merged it with my local version. I was testing the edit in page on github (first time using it). 
I didn't realize it made a separate branch.

**Comment by elight** [comment]
The old version was an ugly spike, no argument.  Looks good.

**Pull request merged**
