### PR TITLE
add travis support

### PR DESCRIPTION
**Pull request by lenary**
This should get rubypair testing on travis. if you go to travis-ci.org , sign in and then enable it from your profile, then it should start building, but i was having issues enabling from the travis switches...

Anyway, that's about it. it will run everything sensible for the tests.

### CODE REVIEW

**Comment by lenary** [comment]
oh. i'll do that in the morning then. sleepy!

**Comment by elight** [comment]
Er... Travis doesn't seem to support github organizations. Rubypair is owned by an organization, rubypair, not by me....

**Comment by elight** [comment]
We still need to set Travis up to use MongoDB, yes?

**Comment by elight** [comment]
Or perhaps not.  Interesting: http://travis-ci.org/#!/rubypair/rubypair

**Pull request merged**
