### PR TITLE
Ignore generated css

### PR DESCRIPTION
**Pull request by lenary**
Just a commit to ignore the generated css.

I mentioned it in #8 but got no feedback before that pull got merged. @elight what do you think?

The downside of doing this is someone has to run compass compile on heroku - and heroku is unlikely to enjoy that.

Perhaps we should just move towards using the asset pipeline normally - or would that mean our heroku server would get inundated very quickly?

All things to consider. don't merge this without discussion first please

### CODE REVIEW

**Comment by lenary** [comment]
So I have now moved the stylesheets into the right place, which means no longer having to run `compass watch` or any of that bullshit.

This will need testing on heroku - it could mean the server gets inundated - but we'll have to see. 

Reading the docs, it seems heroku might precompile the assets when the app is pushed.

**Comment by elight** [comment]
This doesn't appear to be ready yet.  After merging this branch in locally and testing, I'm seeing the following: https://skitch.com/evanlight/farg3/twitter

**Comment by lenary** [comment]
I'm confused by the lines saying the fonts haven't loaded. however, that commit (281f5b9) fixes the issue with the tagify css

**Comment by elight** [comment]
I'll check again later. I merged it into my local master, reset my browser's cache just in case, and loaded the page. That's what I got.

**Comment by elight** [comment]
Interesting. Rendered correctly now.

**Pull request closed without merging**
