### PR TITLE
Rails 3 upgrade

### PR DESCRIPTION
**Pull request by pythonandchips**
Hi,

I've updated the app to use rails 3.1

Couple of things to note,
1. I had to add libnotify and rb-inotify to the gemfile as i'm using ubuntu and growl_notify doesn't work.
2. renamed the user_spec file to user_test. Mainly just to stick with convention and allow the default rake task to operate correctly.
3. I had to add a database name to the mongodb.yml in the production section, other wise rake task simply failed in development mode

I've tested it on heroku and it seems to work fine

Cheers
Colin Gemmell

### CODE REVIEW

**Comment by lenary** [comment]
you probably want to rebase against master as the user_spec has now been moved to the spec/ directory, and i think we're now using rspec.

**Comment by pythonandchips** [comment]
Coolio, will do that toot sweet

**Comment by lenary** [comment]
Also, the guardfile is gone now. that may trip you up... but it shoudn't

**Comment by pythonandchips** [comment]
That's cool.

I'll rebase the now then resubmit the patch once i've tested things out
again.

Cheers

**Pull request closed without merging**
