### PR TITLE
Geocode users

### PR DESCRIPTION
**Pull request by lenary**

### CODE REVIEW

**Comment by lenary** [comment]
Fun times - I don't have enough details to get a yahoo api key, and google requires that we use their geocoding api for stuff on a google map. looks like we'll have to have a small google map on each profile page, and maybe also a map of everyone (that could be fun)

I'm looking into this further

**Comment by lenary** [comment]
Took the plunge - using the google api - i'm now going to code up a page with a map of everyone on rubypair

**Comment by elight** [comment]
Useful but not quite what the ticket calls for. Geocoding means getting coordinates for each user. This could then be used for mapping or for spatial query.

I like the idea of a map although it's a manual sort of spatial query.

**Comment by lenary** [comment]
sadly true, but google requires we use their geocode data for their maps. i have no choice any other way. unless you sign up for a yahoo api key and i rewrite that class.

**Comment by lenary** [comment]
Ok, Reverted!

**Comment by elight** [comment]
Be careful. I intentionally didn't use blank? to avoid Rails dependencies. I haven't done the full test refractor yet. However, imagine everything is tested as a PORO...

**Comment by gaustin** [comment]
The Calendar About Nothing (https://github.com/technoweenie/seinfeld) application uses http://www.geonames.org/ for geocoding. They don't require that you use the data on a map.

Sound like a suitable alternative? (Unless the map is now a desired feature.)

**Comment by lenary** [comment]
@gaustin that actually does sound like a good alternative. When I can find the time, I'll start rewriting the code to use it.

**Comment by elight** [comment]
:D

On Apr 23, 2012, at 6:40 PM, Sam Elliott
reply@reply.github.com
wrote:

**Comment by gaustin** [comment]
@elight @lenary Should we close this?

I'm back to using my personal github more and this is forever on my "mentions"

**Pull request closed without merging**
